### PR TITLE
Add: the German language

### PR DESCRIPTION
**Pull request by Jonaslsn**
When this pull request will be approved, this plugin will be optimized for the German language as well.
In addition, a mistake in the English description of the friends list will be solved.

**File changes**
- Add: German language added
- Fix: In English language updated the note for the friends list

### CODE REVIEW

**Comment by Neodymium7** [comment]
Thanks for the contribution! Can you edit [the source](https://github.com/Neodymium7/BetterDiscordStuff/blob/main/VoiceActivity/src/locales.json) directly instead of the bundled output?

**Comment by Jonaslsn** [comment]
Hi. Of course I hope it matches like this. Unfortunately I did not see that it was already the built version / file. Should I reset the other file again?

**Comment by Neodymium7** [comment]
Yes, it would be best to revert the changes to the bundled file. Thanks!

**Comment by Jonaslsn** [comment]
Ok. Now it should fit.

**Pull request merged**
